<?php

namespace Database\Seeders;

use App\Models\AirlineCabinProfile;
use App\Models\SeatMap;
use App\Models\Aircraft;
use App\Models\TravelClass;
use Illuminate\Database\Seeder;

class SeatMapSeeder extends Seeder
{
    public function run(): void
    {
        // Seed airline-specific seat maps from cabin profiles (generated by AirlineCabinProfileSeeder).
        $profiles = AirlineCabinProfile::with(['airline', 'aircraft', 'travelClass'])->get();

        foreach ($profiles as $profile) {
            $this->generateSeats(
                $profile->aircraft_id,
                $profile->travel_class_id,
                $profile->start_row,
                $profile->end_row,
                $profile->columns,
                $profile->layout_code,
                $profile->exit_rows ?? [],
                $profile->extra_price_exit,
                $profile->airline_id,
            );
        }

        // Seed generic fallback seat maps for aircraft that have no airline-specific profiles.
        // These are used when a flight's airline lacks a cabin profile entry for that aircraft/class.
        $this->seedGenericFallbacks();
    }

    /**
     * Generic fallback seat maps (not tied to any airline).
     * Only created for aircraft/class combinations not already covered by airline profiles.
     */
    private function seedGenericFallbacks(): void
    {
        $b737 = Aircraft::where('model', '737-800')->first();
        $a320 = Aircraft::where('model', 'A320-200')->first();
        $b777 = Aircraft::where('model', '777-300ER')->first();
        $a330 = Aircraft::where('model', 'A330-300')->first();
        $a321 = Aircraft::where('model', 'A321neo')->first();

        $economy  = TravelClass::where('code', 'Y')->first();
        $business = TravelClass::where('code', 'C')->first();
        $first    = TravelClass::where('code', 'F')->first();

        // Boeing 737-800
        if ($b737 && $business) {
            $this->generateSeats($b737->id, $business->id, 1, 4, ['A', 'C', 'D', 'F'], '2-2');
        }
        if ($b737 && $economy) {
            $this->generateSeats($b737->id, $economy->id, 5, 35, ['A', 'B', 'C', 'D', 'E', 'F'], '3-3', [15, 16]);
        }

        // Airbus A320
        if ($a320 && $business) {
            $this->generateSeats($a320->id, $business->id, 1, 4, ['A', 'C', 'D', 'F'], '2-2');
        }
        if ($a320 && $economy) {
            $this->generateSeats($a320->id, $economy->id, 5, 32, ['A', 'B', 'C', 'D', 'E', 'F'], '3-3', [12, 13]);
        }

        // Boeing 777-300ER
        if ($b777 && $first) {
            $this->generateSeats($b777->id, $first->id, 1, 2, ['A', 'D', 'G', 'K'], '1-2-1');
        }
        if ($b777 && $business) {
            $this->generateSeats($b777->id, $business->id, 3, 12, ['A', 'B', 'D', 'E', 'F', 'G', 'J', 'K'], '2-4-2');
        }
        if ($b777 && $economy) {
            $this->generateSeats($b777->id, $economy->id, 13, 50, ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K'], '3-4-3', [25, 26]);
        }

        // Airbus A330
        if ($a330 && $business) {
            $this->generateSeats($a330->id, $business->id, 1, 8, ['A', 'B', 'D', 'G', 'J', 'K'], '2-2-2');
        }
        if ($a330 && $economy) {
            $this->generateSeats($a330->id, $economy->id, 9, 45, ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'K'], '2-4-2', [20, 21]);
        }

        // Airbus A321neo
        if ($a321 && $business) {
            $this->generateSeats($a321->id, $business->id, 1, 3, ['A', 'C', 'D', 'F'], '2-2');
        }
        if ($a321 && $economy) {
            $this->generateSeats($a321->id, $economy->id, 4, 40, ['A', 'B', 'C', 'D', 'E', 'F'], '3-3', [18, 19]);
        }
    }

    private function generateSeats(
        int $aircraftId,
        int $travelClassId,
        int $startRow,
        int $endRow,
        array $cols,
        string $layout,
        array $exitRows = [],
        float $extraPriceExit = 150000,
        ?int $airlineId = null,
    ): void {
        for ($row = $startRow; $row <= $endRow; $row++) {
            foreach ($cols as $index => $col) {
                $isExit = in_array($row, $exitRows);
                $position = 'middle';
                if ($index === 0 || $index === count($cols) - 1) {
                    $position = 'window';
                } elseif ($this->isAisle($index, $cols, $layout)) {
                    $position = 'aisle';
                }

                SeatMap::create([
                    'airline_id'     => $airlineId,
                    'aircraft_id'    => $aircraftId,
                    'travel_class_id' => $travelClassId,
                    'seat_number'    => $row . $col,
                    'row_number'     => $row,
                    'column_letter'  => $col,
                    'position'       => $position,
                    'is_exit_row'    => $isExit,
                    'is_available'   => true,
                    'extra_price'    => $isExit ? $extraPriceExit : 0,
                ]);
            }
        }
    }

    private function isAisle(int $index, array $cols, string $layout): bool
    {
        $parts = explode('-', $layout);
        $currentIndex = 0;
        foreach ($parts as $part) {
            $partSize = (int) $part;
            if ($index === $currentIndex || $index === $currentIndex + $partSize - 1) {
                if ($index !== 0 && $index !== count($cols) - 1) {
                    return true;
                }
            }
            $currentIndex += $partSize;
        }
        return false;
    }
}
